#!/usr/bin/perl

#
# Copyright (C) 2016 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

use strict;
use esmith::Build::CreateLinks  qw(:all);

#
# nethserver-upgrade-tool-update event
#

event_actions('nethserver-upgrade-tool-update', qw(
   initialize-default-databases 00
   nethserver-upgrade-cleankernels 30
));


#
# nethserver-upgrade-tool-prepare event
#

event_actions('nethserver-upgrade-tool-prepare', qw(
    nethserver-upgrade-download 30
    nethserver-upgrade-nsdc 40
    nethserver-upgrade-txcheck 80
));

event_services('nethserver-upgrade-tool-prepare', qw(
    crond stop
));


#
# nethserver-upgrade-tool-reset event
#

event_actions('nethserver-upgrade-tool-reset', qw(
    nethserver-upgrade-cleanup 20
));

event_services('nethserver-upgrade-tool-reset', qw(
    crond start
));


#
# dcipaddr validator
#
validator_actions('dcipaddr', qw(
    ipgreenandbridged 20
));
