#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

/usr/bin/systemctl enable network.service shorewall.service nethserver-config-network.service

/usr/bin/chmod -c +x /sbin/e-smith/nethserver-config-network

/usr/bin/systemctl disable nethserver-system-upgrade.service

/bin/rm -vrf \
    /root/preupgrade \
    /var/tmp/nethserver-upgrade-tool \
    /etc/e-smith/events/upgrade-restore-config \
    /etc/systemd/system/nethserver-system-upgrade.service \
    /etc/e-smith/events/nethserver-system-upgrade
