#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

shopt -s nullglob

echo "[INFO] Apply .rpmnew files"
for F in $(find / -path /var/lib/nethserver -prune -o -type f -name '*.rpmnew'); do
    mv -vf "${F}" "${F%%.rpmnew}"
done

echo "[INFO] Clean up old network configuration"
/etc/e-smith/events/actions/interface-config-reset system-upgrade

echo "[INFO] Clean up udev persistent net rules"
rm -vf /etc/udev/rules.d/70-persistent-net.rules

echo "[INFO] Install the upgrade service at first boot"
cp -vf ./*.service /etc/systemd/system/
cp -av ./nethserver-system-upgrade /etc/e-smith/events/nethserver-system-upgrade
find /etc/e-smith/events/nethserver-system-upgrade -type f -exec chmod +x -c '{}' \;

echo "[INFO] Disable udev automatic updates to networks DB"
chmod -c -x /sbin/e-smith/nethserver-config-network

if [[ -d /etc/e-smith/events/trusted-networks-modify/templates2expand/etc/httpd/conf.d/ ]]; then
    echo "[INFO] Fix httpd startup during trusted-networks-modify event"
    touch /etc/e-smith/events/trusted-networks-modify/templates2expand/etc/httpd/conf.d/default-virtualhost.inc
fi

if [[ -f ./pgpsigs.sed ]]; then
    rpm -qa --qf "%{NVRA} %|DSAHEADER?{%{DSAHEADER:pgpsig}}:{%|RSAHEADER?{%{RSAHEADER:pgpsig}}:{(none}|}|\n" | sed -n -f ./pgpsigs.sed >pkgcleanup.list
    echo "[INFO] Cleanup obsolete packages" $(<pkgcleanup.list)
    rpm -e --nodeps $(<pkgcleanup.list)
    if [[ $? != 0 ]]; then
        for PACKAGE in $(<pkgcleanup.list); do
            if rpm -q "${PACKAGE}" &>/dev/null ; then
                echo "[WARNING] Forcing cleanup of obsolete package ${PACKAGE}"
                rpm -e --nodeps --noscripts ${PACKAGE}
            fi
        done
    fi
fi

if [[ -n "$(echo /etc/e-smith/templates-custom/*)" ]]; then
    echo "[INFO] archiving customized templates to /root/templates-custom.upgrade/"
    mkdir -p /root/templates-custom.upgrade/
    for P in /etc/e-smith/templates-custom/*; do
        mv -vf "${P}" /root/templates-custom.upgrade/
    done
fi

echo "[INFO] Remove .rpmsave files"
find / -path /var/lib/nethserver -prune -o -type f -name '*.rpmsave' -delete

echo "[INFO] Remove chkconfig symlinks"
find /etc/rc.d/ -type l -delete

echo "[INFO] apply systemd presets"
systemctl --root=/ preset-all

echo "[INFO] Enable the upgrade service at first boot"
systemctl --root=/ enable nethserver-system-upgrade.service

if [[ -d /var/lib/ldap ]]; then
    echo "[INFO] Remove OpenLDAP databases"
    find /var/lib/ldap -type f -delete
fi

if [[ -d /var/lib/mysql ]]; then
    echo "[INFO] Remove MySQL databases"
    rm -rf /var/lib/mysql/*
fi

echo "[INFO] clean up Server Manager session and cache"
rm -rf /var/cache/nethserver-httpd-admin/*
