#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

cd /var/lib/system-upgrade || exit 1
[[ -f package.list ]] || exit 1
rpm --nodeps --force -i --test $(<package.list)
if [[ $? != 0 ]]; then
    echo "[ERROR] the RPM transaction test failed"
    exit 1
fi

echo "[INFO] $(wc -l <package.list) packages ready for the upgrade. Reboot to proceed."
