#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

shopt -s nullglob

cd /var/lib/system-upgrade || exit 1

if [[ ! -f package.list ]]; then
    echo "[ERROR] could not read the package list"
    exit 1
fi

rspace=$(rpm --queryformat='%{SIZE} %{NAME}\n' -qp $(<package.list) /var/tmp/nethserver-upgrade-tool/*.rpm | awk '{size += $1} END{print int(size/1024)+1}')
fspace_root=$(df -P -k / | awk 'NR==2 {print $4}')

if ((fspace_root < rspace)); then
    echo "[ERROR] not enough free disk space (required $rspace, free $fspace_root)" 1>&2
    exit 1
fi

echo "[NOTICE] required space $rspace, free space $fspace_root"

rpm --nodeps --force -i --test $(<package.list) /var/tmp/nethserver-upgrade-tool/*.rpm
if [[ $? != 0 ]]; then
    echo "[ERROR] the RPM transaction test failed" 1>&2
    exit 1
fi

echo "[INFO] $(wc -l <package.list) packages ready for the upgrade. Reboot to proceed."
