#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

nsdcIpAddress=$(/sbin/e-smith/config getprop upgrade-tool NsdcIpAddress)
nsdcBridge=$(/sbin/e-smith/config getprop upgrade-tool NsdcBridge)
sssdRealm=$(/sbin/e-smith/config getprop upgrade-tool SssdRealm)
reposet=$(/sbin/e-smith/config getprop upgrade-tool RepoSet)
if [[ -z ${nsdcIpAddress} || -z ${nsdcBridge} || -z ${sssdRealm} || -z ${reposet} ]]; then
    exit 0
fi

echo "[NOTICE] Download and prepare NSDC, the local Active Directory accounts provider"

set -e -o pipefail

rpmdir=/var/tmp/nethserver-upgrade-tool/
yumugroot=$(mktemp -d)
mkdir -p ${rpmdir}
trap "rm -rf ${yumugroot}" EXIT
trap "rm -rf ${rpmdir}" ERR
mkdir -p ${yumugroot}/etc/yum/vars
mkdir -p ${yumugroot}/etc/yum.repos.d
rsync -ai --delete /etc/yum/vars/* ${yumugroot}/etc/yum/vars
rsync -ai --delete /etc/yum.repos.d/ ${yumugroot}/etc/yum.repos.d

pushd ${rpmdir}
yumdownloader -y --installroot=${yumugroot} --disablerepo=\* --enablerepo=${reposet}-\* nethserver-dc | /usr/libexec/nethserver/ptrack-upgrade-nsdc
rpm2cpio nethserver-dc-*.rpm | cpio -id ./usr/lib/nethserver-dc/ns-samba-\*.rpm
popd

sambarpm=$(find ${rpmdir} -type f -name 'ns-samba-*.rpm')
if [[ ! -f "${sambarpm}" ]]; then
    echo "[ERROR] Could not find ns-samba RPM to prepare nsdc chroot"
    exit 1
fi

trap "rm -rf ${yumugroot} ${sambarpm}" EXIT

nsroot=/var/lib/machines/nsdc
if [[ ! -d ${nsroot} ]]; then
    trap "rm -rf ${nsroot} ${rpmdir}" ERR
    mkdir -p ${nsroot}/etc/yum/vars
    mkdir -p ${nsroot}/var/log/journal
    mkdir -p ${nsroot}/run
    ln -sfT ../run ${nsroot}/var/run
    mkdir -p ${nsroot}/etc/systemd/network
    cp -f /etc/yum/vars/* ${nsroot}/etc/yum/vars
    rpm --root=${nsroot} --import /etc/pki/rpm-gpg/*
    yum -y --releasever=7 --installroot=${nsroot} install ${sambarpm} centos-release systemd-networkd bind-utils ntp
    rm -f ${nsroot}/etc/krb5.conf
fi
