#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

pkglist=/var/lib/nethserver/backup/package-list
reposet=$(/sbin/e-smith/config getprop upgrade-tool RepoSet)
yumugroot=/var/tmp/nethserver-upgrade-tool
postupgraded=/root/preupgrade/postupgrade.d

if [[ ! -d ${postupgraded} ]]; then
    echo "[ERROR] The directory ${postupgraded} can't be found. Reinstall nethserver-upgrade-tool."
    exit 1
fi

# Mark all known RPM signatures for upgrade/removal, excluding grub:
echo '/^grub-/ d' > ${postupgraded}/pgpsigs.sed
rpm -qa --qf "%|DSAHEADER?{%{DSAHEADER:pgpsig}}:{%|RSAHEADER?{%{RSAHEADER:pgpsig}}:{(none}|}| %{NVRA}\n" | grep -E '[a-f0-9]{16}' -o | sort | uniq | sed '/^$/ d ; s,^,/, ; s,$,/ {s/ .*$//;p},'  >> ${postupgraded}/pgpsigs.sed

# Save the MAC/NIC assignment:
/usr/libexec/nethserver/nic-info > ${postupgraded}/nicinfo_old.list

/sbin/e-smith/backup-config
if [[ $? != 0 || ! -f ${pkglist} ]]; then
    echo "[ERROR] the configuration backup procedure failed"
    exit 1
fi

/sbin/e-smith/signal-event pre-backup-data
if [[ $? != 0 ]]; then
    echo "[ERROR] the pre-backup-data event failed"
    exit 1
fi

rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-${reposet}bundle

redhat-upgrade-tool --network 7 --instrepo=${reposet}-instrepo --force --enablerepo=${reposet}-\*
if [[ $? != 0 ]]; then
    echo "[ERROR] the redhat-upgrade tool failed"
    exit 1
fi

# Migrate packages from NS 6 to NS 7
# See: http://docs.nethserver.org/en/v7/release_notes.html#discontinued-packages
packages=$(sed -r \
   -e '/^file .+ is not owned by any package/ d' \
   -e '/^nethserver-upgrade-tool/ d' \
   -e 's/^nethserver-vpn$/nethserver-openvpn\nnethserver-ipsec-tunnels/'  \
   -e 's/^nethserver-collectd-web$/nethserver-cgp/' \
   -e 's/^nethserver-fetchmail$/nethserver-getmail/' \
   -e 's/^nethserver-snort$/nethserver-suricata/' \
   -e 's/^nethserver-ibays$/nethserver-virtualhosts\nnethserver-samba/' \
   -e '/^nethserver-c-icap$/d' \
   -e '/^nethserver-ipsec$/d' \
/var/lib/nethserver/backup/package-list | tr $'\n' ' ')

rm -rf ${yumugroot}
mkdir -p ${yumugroot}/etc/yum/vars
mkdir -p ${yumugroot}/etc/yum.repos.d
rsync -ai --delete /etc/yum/vars/* ${yumugroot}/etc/yum/vars
rsync -ai --delete /etc/yum.repos.d/ ${yumugroot}/etc/yum.repos.d

cd /var/lib/system-upgrade
yum -y --downloadonly --downloaddir . --installroot=${yumugroot} --disablerepo=\* --enablerepo=${reposet}-\* install @centos-minimal @nethserver-iso ${packages}
find . -name '*.rpm' -printf '%f\n' > package.list

echo "[INFO] $(wc -l <package.list) packages ready for the upgrade. Reboot to proceed."
