#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

set -x

pkglist=/var/lib/nethserver/backup/package-list
reposet=$(/sbin/e-smith/config getprop upgrade-tool RepoSet)
downloaddir=/var/lib/nethserver-upgrade-tool

/sbin/e-smith/backup-config
if [[ $? != 0 || ! -f ${pkglist} ]]; then
    echo "[ERROR] the configuration backup procedure failed"
    exit 1
fi

rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-${reposet}bundle

redhat-upgrade-tool --network 7 --force --enablerepo=${reposet}-\*

rm -rf ${downloaddir}
mkdir ${downloaddir}
yum -y --downloadonly --downloaddir ${downloaddir} --installroot=${downloaddir} --disablerepo=\* --enablerepo=${reposet}-\* install @centos-minimal @nethserver-iso $(grep ^nethserver ${pkglist})

