#!/bin/bash

#
# Copyright (C) 2018 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# Estimated /boot space (upgrade image + boot) ~ 160MB
kspace=163840

# /boot free space
fspace_boot=$(df -P -k /boot | awk 'NR==2 {print $4}')

if ((fspace_boot < kspace)); then
    echo "Required /boot space:" $((kspace/1024)) "MB"
    exit 3
fi